### ISSUE TITLE
关于IA

### ISSUE THREAD

**Issue by tuoli9** [jpzhang1810/NAA#1]
能解释一下为什么在每一次迭代时只计算IA一次吗？

**Comment by Unkrible** [comment]
page4 Eq(2)下面那段 assume that the two parts are linearly independent, i.e., the two gradient sequences should have zero covariance.
通过这个假设, 将x变化对输出F的影响(即, A)拆分为x对中间层y的影响(即, $\delta y$)和y对输出F的影响 (即, IA).
因为已经假设两者linearly independent, 所以y对F的影响(即, IA)不需要重复计算了, 只要计算一次.
(我不是作者
