### ISSUE TITLE
关于IA计算过程

### ISSUE THREAD

**Issue by OUTOFTEN** [jpzhang1810/NAA#2]
作者提供的代码中，第256行，好像在迭代计算IA的过程中加入了随机噪声，这一点好像在论文中并没有体现。请问这个随机噪声有什么讲究么？我用pytorch复现的过程中发现，没有这个随机噪声NAA的效果还不如FIA。

**Comment by umiskky** [comment]
是不是与下面这篇文章中的TAIG-R类似，通过随机数来获得一个随机的积分路径
Huang, Y., & Kong, A. (2022). Transferable Adversarial Attack based on Integrated Gradients. ICLR. https://doi.org/10.48550/arxiv.2205.13152

**Comment by OUTOFTEN** [comment]
> 是不是与下面这篇文章中的TAIG-R类似，通过随机数来获得一个随机的积分路径 Huang, Y., & Kong, A. (2022). Transferable Adversarial Attack based on Integrated Gradients. ICLR. https://doi.org/10.48550/arxiv.2205.13152

是的，这篇文章我也看过，非常类似。但对于NAA来说，这个随机噪声好像显得更为重要，这个随机噪声可以帮助NAA提高很多的迁移性，以至于可以超越FIA（依据文章），但是，从我的复现结果来看，这个噪声的大小或者分布应该有些讲究，我不清楚作者添加的这个随机噪声有什么理论指导么？如果按照论文里给的伪代码，或者作者提供的代码，添加一个高斯分布的随机噪声，至少在正常训练的模型上很难超越FIA的性能。添加高斯分布的随机噪声也只能达到和FIA旗鼓相当的水平。

**Comment by ICSE2023-code** [comment]
你好，本文提供了一种基于attribution的方式来进行feature-level attack。在代码中使用的是smoothgrad来计算attribution，参考文中引用[25] 。

**Comment by jpzhang1810** [comment]
你好，本文提供了一种基于attribution来进行特征攻击的算法。代码是根据Smoothgrad来进行实现，可参考文中的引用25。

**Comment by britney-code** [comment]
> 作者提供的代码中，第256行，好像在迭代计算IA的过程中加入了随机噪声，这一点好像在论文中并没有体现。请问这个随机噪声有什么讲究么？我用pytorch复现的过程中发现，没有这个随机噪声NAA的效果还不如FIA。

你好，我正在看NAA的论文，如果您使用pytorch实现了该论文的算法，能否发给我一份🥺，感激不敬！

**Comment by britney-code** [comment]
> > 是不是与下面这篇文章中的TAIG-R类似，通过随机数来获得一个随机的积分路径 Huang, Y., & Kong, A. (2022). Transferable Adversarial Attack based on Integrated Gradients. ICLR. [https://doi.org/10.48550/arxiv.2205.13152[  ](https://sci-hub.se/10.48550/arxiv.2205.13152)](https://doi.org/10.48550/arxiv.2205.13152)
> 
> 是的，这篇文章我也看过，非常类似。但对于NAA来说，这个随机噪声好像显得更为重要，这个随机噪声可以帮助NAA提高很多的迁移性，以至于可以超越FIA（依据文章），但是，从我的复现结果来看，这个噪声的大小或者分布应该有些讲究，我不清楚作者添加的这个随机噪声有什么理论指导么？如果按照论文里给的伪代码，或者作者提供的代码，添加一个高斯分布的随机噪声，至少在正常训练的模型上很难超越FIA的性能。添加高斯分布的随机噪声也只能达到和FIA旗鼓相当的水平。

论文貌似是基于IG的归因方法，SMoothGrad用于去噪的目的，不去噪显示的图像会有很多噪点，基于梯度的都会遇到噪声问题，FIA的聚集梯度也是为了显示更加清晰的图像，IG的归因方法比普通梯度方法要更好，我的理解

**Comment by OUTOFTEN** [comment]
> > 作者提供的代码中，第256行，希望在迭代计算IA的过程中加入随机噪声，这一点希望在论文中并没有体现。请问这个随机噪声有什么讲究吗？我用pytorch复现的过程中发现，没有这种随机噪声NAA的效果还不如FIA。
> 
> 你好，我正在看 NAA 的论文，如果你使用 pytorch 实现了该论文的算法，能否开发给我一份🥺，感激不敬！

你好！我复现的pytorch版本已开源在这里：https://github.com/OUTOFTEN/adversarial-attack/blob/master/attack_algorithem/NAA.py。由于最近比较忙，且该本地仓库已经逐渐庞大，而我还没来得及整理，因此，我只放了攻击的核心代码，也没来得及写注释，如有疑问欢迎讨论。值得注意的是，作者使用的smoothgrad在一定噪声幅度下是有效的（这和图像数据本身有关），好像smoothgrad的论文也说到了这一点，并不是随便加噪声都有用。目前我只验证了我代码里的噪声幅度在图像数据范围处于[-1,1]时有效。

**Comment by britney-code** [comment]
> > > 作者提供的代码中，第256行，希望在迭代计算IA的过程中加入随机噪声，这一点希望在论文中并没有体现。请问这个随机噪声有什么讲究吗？我用pytorch复现的过程中发现，没有这种随机噪声NAA的效果还不如FIA。
> > 
> > 
> > 你好，我正在看 NAA 的论文，如果你使用 pytorch 实现了该论文的算法，能否开发给我一份🥺，感激不敬！
> 
> 你好！我复现的pytorch版本已开源在这里：[https://github.com/OUTOFTEN/adversarial-attack/blob/master/attack_algorithem/NAA.py。由于最近比较忙，且该本地仓库已经逐渐庞大，而我还没来得及整理，因此，我只放了攻击的核心代码，也没来得及写注释，如有疑问欢迎讨论。值得注意的是，作者使用的smoothgrad在一定噪声幅度下是有效的（这和图像数据本身有关），好像smoothgrad的论文也说到了这一点，并不是随便加噪声都有用。目前我只验证了我代码里的噪声幅度在图像数据范围处于[-1,1]时有效。](https://github.com/OUTOFTEN/adversarial-attack/blob/master/attack_algorithem/NAA.py%E3%80%82%E7%94%B1%E4%BA%8E%E6%9C%80%E8%BF%91%E6%AF%94%E8%BE%83%E5%BF%99%EF%BC%8C%E4%B8%94%E8%AF%A5%E6%9C%AC%E5%9C%B0%E4%BB%93%E5%BA%93%E5%B7%B2%E7%BB%8F%E9%80%90%E6%B8%90%E5%BA%9E%E5%A4%A7%EF%BC%8C%E8%80%8C%E6%88%91%E8%BF%98%E6%B2%A1%E6%9D%A5%E5%BE%97%E5%8F%8A%E6%95%B4%E7%90%86%EF%BC%8C%E5%9B%A0%E6%AD%A4%EF%BC%8C%E6%88%91%E5%8F%AA%E6%94%BE%E4%BA%86%E6%94%BB%E5%87%BB%E7%9A%84%E6%A0%B8%E5%BF%83%E4%BB%A3%E7%A0%81%EF%BC%8C%E4%B9%9F%E6%B2%A1%E6%9D%A5%E5%BE%97%E5%8F%8A%E5%86%99%E6%B3%A8%E9%87%8A%EF%BC%8C%E5%A6%82%E6%9C%89%E7%96%91%E9%97%AE%E6%AC%A2%E8%BF%8E%E8%AE%A8%E8%AE%BA%E3%80%82%E5%80%BC%E5%BE%97%E6%B3%A8%E6%84%8F%E7%9A%84%E6%98%AF%EF%BC%8C%E4%BD%9C%E8%80%85%E4%BD%BF%E7%94%A8%E7%9A%84smoothgrad%E5%9C%A8%E4%B8%80%E5%AE%9A%E5%99%AA%E5%A3%B0%E5%B9%85%E5%BA%A6%E4%B8%8B%E6%98%AF%E6%9C%89%E6%95%88%E7%9A%84%EF%BC%88%E8%BF%99%E5%92%8C%E5%9B%BE%E5%83%8F%E6%95%B0%E6%8D%AE%E6%9C%AC%E8%BA%AB%E6%9C%89%E5%85%B3%EF%BC%89%EF%BC%8C%E5%A5%BD%E5%83%8Fsmoothgrad%E7%9A%84%E8%AE%BA%E6%96%87%E4%B9%9F%E8%AF%B4%E5%88%B0%E4%BA%86%E8%BF%99%E4%B8%80%E7%82%B9%EF%BC%8C%E5%B9%B6%E4%B8%8D%E6%98%AF%E9%9A%8F%E4%BE%BF%E5%8A%A0%E5%99%AA%E5%A3%B0%E9%83%BD%E6%9C%89%E7%94%A8%E3%80%82%E7%9B%AE%E5%89%8D%E6%88%91%E5%8F%AA%E9%AA%8C%E8%AF%81%E4%BA%86%E6%88%91%E4%BB%A3%E7%A0%81%E9%87%8C%E7%9A%84%E5%99%AA%E5%A3%B0%E5%B9%85%E5%BA%A6%E5%9C%A8%E5%9B%BE%E5%83%8F%E6%95%B0%E6%8D%AE%E8%8C%83%E5%9B%B4%E5%A4%84%E4%BA%8E%5B-1,1%5D%E6%97%B6%E6%9C%89%E6%95%88%E3%80%82)

great! 非常感谢。

**Comment by britney-code** [comment]
> > > 作者提供的代码中，第256行，希望在迭代计算IA的过程中加入随机噪声，这一点希望在论文中并没有体现。请问这个随机噪声有什么讲究吗？我用pytorch复现的过程中发现，没有这种随机噪声NAA的效果还不如FIA。
> > 
> > 
> > 你好，我正在看 NAA 的论文，如果你使用 pytorch 实现了该论文的算法，能否开发给我一份🥺，感激不敬！
> 
> 你好！我复现的pytorch版本已开源在这里：[https://github.com/OUTOFTEN/adversarial-attack/blob/master/attack_algorithem/NAA.py。由于最近比较忙，且该本地仓库已经逐渐庞大，而我还没来得及整理，因此，我只放了攻击的核心代码，也没来得及写注释，如有疑问欢迎讨论。值得注意的是，作者使用的smoothgrad在一定噪声幅度下是有效的（这和图像数据本身有关），好像smoothgrad的论文也说到了这一点，并不是随便加噪声都有用。目前我只验证了我代码里的噪声幅度在图像数据范围处于[-1,1]时有效。](https://github.com/OUTOFTEN/adversarial-attack/blob/master/attack_algorithem/NAA.py%E3%80%82%E7%94%B1%E4%BA%8E%E6%9C%80%E8%BF%91%E6%AF%94%E8%BE%83%E5%BF%99%EF%BC%8C%E4%B8%94%E8%AF%A5%E6%9C%AC%E5%9C%B0%E4%BB%93%E5%BA%93%E5%B7%B2%E7%BB%8F%E9%80%90%E6%B8%90%E5%BA%9E%E5%A4%A7%EF%BC%8C%E8%80%8C%E6%88%91%E8%BF%98%E6%B2%A1%E6%9D%A5%E5%BE%97%E5%8F%8A%E6%95%B4%E7%90%86%EF%BC%8C%E5%9B%A0%E6%AD%A4%EF%BC%8C%E6%88%91%E5%8F%AA%E6%94%BE%E4%BA%86%E6%94%BB%E5%87%BB%E7%9A%84%E6%A0%B8%E5%BF%83%E4%BB%A3%E7%A0%81%EF%BC%8C%E4%B9%9F%E6%B2%A1%E6%9D%A5%E5%BE%97%E5%8F%8A%E5%86%99%E6%B3%A8%E9%87%8A%EF%BC%8C%E5%A6%82%E6%9C%89%E7%96%91%E9%97%AE%E6%AC%A2%E8%BF%8E%E8%AE%A8%E8%AE%BA%E3%80%82%E5%80%BC%E5%BE%97%E6%B3%A8%E6%84%8F%E7%9A%84%E6%98%AF%EF%BC%8C%E4%BD%9C%E8%80%85%E4%BD%BF%E7%94%A8%E7%9A%84smoothgrad%E5%9C%A8%E4%B8%80%E5%AE%9A%E5%99%AA%E5%A3%B0%E5%B9%85%E5%BA%A6%E4%B8%8B%E6%98%AF%E6%9C%89%E6%95%88%E7%9A%84%EF%BC%88%E8%BF%99%E5%92%8C%E5%9B%BE%E5%83%8F%E6%95%B0%E6%8D%AE%E6%9C%AC%E8%BA%AB%E6%9C%89%E5%85%B3%EF%BC%89%EF%BC%8C%E5%A5%BD%E5%83%8Fsmoothgrad%E7%9A%84%E8%AE%BA%E6%96%87%E4%B9%9F%E8%AF%B4%E5%88%B0%E4%BA%86%E8%BF%99%E4%B8%80%E7%82%B9%EF%BC%8C%E5%B9%B6%E4%B8%8D%E6%98%AF%E9%9A%8F%E4%BE%BF%E5%8A%A0%E5%99%AA%E5%A3%B0%E9%83%BD%E6%9C%89%E7%94%A8%E3%80%82%E7%9B%AE%E5%89%8D%E6%88%91%E5%8F%AA%E9%AA%8C%E8%AF%81%E4%BA%86%E6%88%91%E4%BB%A3%E7%A0%81%E9%87%8C%E7%9A%84%E5%99%AA%E5%A3%B0%E5%B9%85%E5%BA%A6%E5%9C%A8%E5%9B%BE%E5%83%8F%E6%95%B0%E6%8D%AE%E8%8C%83%E5%9B%B4%E5%A4%84%E4%BA%8E%5B-1,1%5D%E6%97%B6%E6%9C%89%E6%95%88%E3%80%82)
FIA的pytorch代码能提供一份吗？ 这对我很有用🥺
