### ISSUE TITLE
其他模型的中间层参数怎么设置？

### ISSUE THREAD

**Issue by bytedanced** [jpzhang1810/NAA#3]
作者，你好，可以给一下论文中其他几个网络的中间层参数设置吗？

**Comment by icml2023-6375** [comment]
你好，谢谢关注！
模型和中间层参数是这么设置的。我同时也会更新readme，感谢提醒。

inception_v3
InceptionV3/InceptionV3/Mixed_5b/concat

inception_v4
InceptionV4/InceptionV4/Mixed_5e/concat

inception_resnet_v2
InceptionResnetV2/InceptionResnetV2/Conv2d_4a_3x3/Relu

resnet_v2_152
resnet_v2_152/block2/unit_8/bottleneck_v2/add

**Comment by jpzhang1810** [comment]
你好，谢谢关注！
模型和中间层参数是这么设置的。我同时也会更新readme，感谢提醒。

inception_v3
InceptionV3/InceptionV3/Mixed_5b/concat

inception_v4
InceptionV4/InceptionV4/Mixed_5e/concat

inception_resnet_v2
InceptionResnetV2/InceptionResnetV2/Conv2d_4a_3x3/Relu

resnet_v2_152
resnet_v2_152/block2/unit_8/bottleneck_v2/add
